### ISSUE TITLE
Add Disabling of Name Labels by Server

### ISSUE THREAD

**Issue by Saptortacus** [OutlawByteStudios/Persistent-Kingdoms#599]

**Comment by Thomas-Smyth** [comment]
Do we know what other effects changing the game mode will have? I would not be surprised if there are other hardcoded changes that may raise other issues.

**Comment by Saptortacus** [comment]
@Thomas-Smyth basically, the game mode Deathmatch inherits pretty much everything from Conquest. There are some pieces of code that make players enemies if Deathmatch is chosen.

**Comment by WilliamTheBear** [comment]
Tested today.
